# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATTData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('memory', models.CharField(max_length=256)),
                ('sku_id', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
                ('imageUrl', models.URLField()),
            ],
            options={
                'verbose_name': 'Data extracted from AT&T',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlobalMobilePhoneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('modelName', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Mobile phone Model',
                'managed': True,
                'verbose_name_plural': 'Mobile Phone Models',
            },
        ),
        migrations.CreateModel(
            name='GlobalMobilePhones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=256)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('imageUrl', models.URLField()),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilewiz.GlobalMobilePhoneModel')),
            ],
            options={
                'verbose_name': 'Mobile Phone',
                'managed': True,
                'verbose_name_plural': 'Mobile Phones',
            },
        ),
        migrations.CreateModel(
            name='TMobileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('memory', models.CharField(max_length=256)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
                ('imageUrl', models.URLField()),
            ],
            options={
                'verbose_name': 'Data extracted from TMobile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerizonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('memory', models.CharField(max_length=256)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
                ('imageUrl', models.URLField()),
            ],
            options={
                'verbose_name': 'Data extracted from Verizon',
                'managed': True,
            },
        ),
    ]
