# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mobilewiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATTData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('memory', models.CharField(max_length=256)),
                ('sku_id', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Data extracted from AT&T',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Mobile phone Selling Companies',
                'managed': True,
                'verbose_name_plural': 'Mobile Phones Selling companies',
            },
        ),
        migrations.CreateModel(
            name='GlobalMobilePhoneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Mobile phone',
                'managed': True,
                'verbose_name_plural': 'Mobile Phones',
            },
        ),
        migrations.CreateModel(
            name='GlobalMobilePhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilewiz.Companies')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilewiz.GlobalMobilePhoneModel')),
            ],
            options={
                'verbose_name': 'Mobile Phone',
                'managed': True,
                'verbose_name_plural': 'Mobile Phones',
            },
        ),
        migrations.CreateModel(
            name='GlobalSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Phone Specifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TMobileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('memory', models.CharField(max_length=256)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Data extracted from TMobile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerizonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=256)),
                ('memory', models.CharField(max_length=256)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_of_installments', models.IntegerField()),
                ('brand', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Data extracted from Verizon',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
